// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/react/react-addons-css-transition-group.d.ts
declare namespace __React {
    export var addons: typeof __React.__Addons;
}
